apiVersion: v2
name: krbtest
description: A Helm chart for Kubernetes
type: application
version: 1.2.0

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
