name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

# Restrict default permissions for GITHUB_TOKEN
# Default workflows have read and write permissions for all scopes
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  issues: write
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm i -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/error @eshepelyuk/semantic-release-helm-oci -D
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: Kevin Benton
          GIT_AUTHOR_EMAIL: krbenton@icloud.com
          GIT_COMMITTER_NAME: Kevin Benton
          GIT_COMMITTER_EMAIL: krbenton@icloud.com
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: semantic-release
